name: harrods-build
on:
  pull_request_target:
    types:
      - closed
    branches:
      - dev
    paths:
      - stat/**
jobs:
  harrods-build:
    if: github.event.pull_request.merged == true
    uses: ./.github/workflow/harrods-build.yml