name: manual-build
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'
jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - name: hello world
        run: echo "hello world"
