name: stat-build
on:
  workflow_dispatch:
  pull_request_target:
    types:
      - closed
    branches:
      - dev
    paths:
      - stat/**
jobs:
  stat-build:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Install JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Install Kotlin
        run: sudo snap install --classic kotlin

      # 프로젝트 빌드
      - name: Build
        run: ./gradlew :stat:build